# Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
# the two matrices have the same number of rows and columns.
result = np.array(X) + np.array(Y)

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


# 2.Write a Python Program to Multiply Two Matrices?

In [3]:
# The product of two matrices A and B is defined if the number of columns of A is equal to the number of rows of B.
import numpy as np

A = [[1, 2, 3],            # A is 3*3 matrix
    [4, 5, 6],
    [7, 8, 9]]

B = [[12, 11, 10, 9],          # B is 3*4 matrix
    [8, 7, 6, 5],
    [4, 3, 2, 1]]

result = np.dot(A,B)        # result will be 3*4 matrix(3/3*3/4=3*4)

for r in result:
    print(r)


[40 34 28 22]
[112  97  82  67]
[184 160 136 112]


# 3.Write a Python Program to Transpose a Matrix?

In [18]:
# Transpose of a matrix is obtained by changing rows to columns and columns to rows.
# below code is for 4*4 matrix
N = 4

def transpose(A):
    for i in range(N):
        for j in range(i+1, N):
             A[i][j], A[j][i] = A[j][i], A[i][j]
    print("Modified matrix is")
    for i in range(N):
        for j in range(N):
            print(A[i][j], " ", end='')
        print()

A = [ [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]]
transpose(A)

Modified matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


In [20]:
A=np.array([ [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]])
np.transpose(A)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

# 4.Write a Python Program to Sort Words in Alphabetic Order?

In [30]:
words=input(" enter words separated by space: ").split()
words.sort()
y=" ".join(words)
print(f"after sorting words {y}")

 enter words separated by space: girl can do for a boy
after sorting words a boy can do for girl


# 5.Write a Python Program to Remove Punctuation From a String?

In [1]:
x=str(input(" enter string "))
pun='''.,;:?'!_()"[]/-''' 
result=""
for i in x:
    if i not in pun:
        result +=i     
print(x)
print(result)

 enter string hi! 'how,"dy.?
hi! 'how,"dy.?
hi howdy
